### ISSUE TITLE
Catalogue?

### ISSUE THREAD

**Issue by lopezelpesado** [fac22/FACTube#42]
I'm curious about the Catalogue component that doesn't get used anywhere. What is it? What was it? What was happening with this line?

[// loadCatalogue();  Bad!!! Maxxes out API key](https://github.com/fac22/FACTube/blob/ee8b9cfdf588fb16bbffc031033a69350bf85464/components/Catalogue.js#L22)

**Comment by 0bubbles0** [comment]
That whole function was wrong: when we called it, it was an eternal loop and immediately maxxed out our API key. We left it there commented out as a reminder not to try that again 😆 

At the moment, we show the catalogue directly in index.js
